#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/webserver  
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Configure Nginx for chatapp
      template:
        src: ~/roletest/roles/webserver/templates/chatapp_nginx.j2
        dest: /etc/nginx/sites-available/chatapp
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Enable chatapp Nginx config
      file:
        src: /etc/nginx/sites-available/chatapp
        dest: /etc/nginx/sites-enabled/chatapp
        state: link
        force: yes
      notify: restart nginx
